#!/bin/bash
set -e

mkdir -p "${APP_DATA_DIR}/data/unifi-data"
mkdir -p "${APP_DATA_DIR}/data/mongodb"

cat > "${APP_DATA_DIR}/data/init-mongo.sh" << 'MONGOEOF'
#!/bin/bash
if which mongosh > /dev/null 2>&1; then
  mongo_init_bin='mongosh'
else
  mongo_init_bin='mongo'
fi
"${mongo_init_bin}" <<EOF
use unifi
db.createUser({
  user: "unifi",
  pwd: "unifipwd123",
  roles: [
    { db: "unifi", role: "dbOwner" },
    { db: "unifi_stat", role: "dbOwner" }
  ]
})
EOF
MONGOEOF
chmod +x "${APP_DATA_DIR}/data/init-mongo.sh"